### ISSUE TITLE
Where is gtest/gtest.h?

### ISSUE THREAD

**Issue by lawabider** [renestein/Rstein.AsyncCpp#13]
I am struggling. Where is gtest.h?
Update: ok it looks like I had to include Google's testing.
BTW it's great that someone is doing a C++ equivalent of this stuff from c#, thanks.

**Comment by renestein** [comment]
Hi @lawabider , 
thanks for your interest.
Yes, gtest.h is from Google Test.
You can install Google Test using the vcpkg. (https://github.com/microsoft/vcpkg)

```
vcpkg install googletest
vcpkg install googletest:x64-windows
```
